export enum TASKS_SORT_KEYS {
    BY_RANG_JUNIOR = "BY_RANG_JUNIOR",
    BY_RANG_MIDDLE = "BY_RANG_MIDDLE",
    BY_RANG_SENIOR = "BY_RANG_SENIOR",
    BY_COMPLETE_SCORE = "BY_COMPLETE_SCORE",
    BY_TITLE = "BY_TITLE",
}

export enum MY_TASKS_SORT_KEYS {
    BY_RANG_JUNIOR = "BY_RANG_JUNIOR",
    BY_RANG_MIDDLE = "BY_RANG_MIDDLE",
    BY_RANG_SENIOR = "BY_RANG_SENIOR",
    BY_COMPLETE_SCORE = "BY_COMPLETE_SCORE",
    BY_TITLE = "BY_TITLE",
}

export enum DEVS_SORT_KEYS {
    BY_JUNIOR = "BY_JUNIOR",
    BY_MIDDLE = "BY_MIDDLE",
    BY_SENIOR = "BY_SENIOR",
    BY_HIGH_RATING = "BY_HIGH_RATING",
    BY_LOW_RATING = "BY_LOW_RATING",
    BY_TASKS_COUNT = "BY_TASKS_COUNT",
    BY_TAKEN_TASKS = "BY_TAKEN_TASKS"
}